train_defaults:
  num_epochs: 1000
  BATCH_SIZE: 4 
  OVERFIT_TO_TRAIN_SPLIT: false
  # BM_NAME: L3SFBenchmark
  BM_NAME: PolyUDBIIBenchmark
  FILTER: null
  WARMUP_EPOCHS: 10
  WARMUP_K_EPOCHS: 2
  LR_DECAY: 0.5
  PRETRAINED_PATH: ""
  CHECKPOINT_PATH: checkpoint2
  LOG_DIR: logs/tensorboard
  start_epoch: 0

policy_defaults:
  PERM_LOSS: focal
  FOCAL_GAMMA: 2.0
  DETECT_ANOMALY: true

data_defaults:
  dataset_len: 640
  train_root: dataset/Poly2/DBII
  # train_root: dataset/L3SF_V2/L3-SF
